-- 코드를 입력하세요
# 1. 리뷰를 가장 많이 작성한 회원 찾기
# 2. 그 회원의 리뷰 조회
SELECT MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY COUNT(*) DESC
LIMIT 1
;

SELECT m.MEMBER_NAME, r.REVIEW_TEXT, r.REVIEW_DATE
FROM REST_REVIEW r
LEFT JOIN MEMBER_PROFILE m ON r.MEMBER_ID=m.MEMBER_ID
WHERE r.MEMBER_ID = (SELECT MEMBER_ID
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(*) DESC
        LIMIT 1)
ORDER BY r.REVIEW_DATE, r.REVIEW_TEXT
;