-- 코드를 작성해주세요
SELECT MAX(SIZE_OF_COLONY), YEAR(DIFFERENTIATION_DATE) AS YEAR
FROM ECOLI_DATA
GROUP BY YEAR(DIFFERENTIATION_DATE)
;

SELECT YEAR(e.DIFFERENTIATION_DATE) AS YEAR, j.MAX_SIZE - e.SIZE_OF_COLONY AS YEAR_DEV, e.ID
FROM ECOLI_DATA e
LEFT JOIN (SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE, YEAR(DIFFERENTIATION_DATE) AS YEAR
        FROM ECOLI_DATA
        GROUP BY YEAR(DIFFERENTIATION_DATE)
    ) j ON j.YEAR = YEAR(e.DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV
;