-- 코드를 입력하세요
# 1. 2021년에 가입한 회원들 찾기
# 2. 그 회원들 중 상품을 구매한 회원수와 회원의 비율 찾기
SELECT USER_ID
FROM USER_INFO
WHERE YEAR(JOINED) = '2021'
;

SELECT o.*
FROM USER_INFO u
RIGHT JOIN ONLINE_SALE o ON u.USER_ID=o.USER_ID
WHERE YEAR(u.JOINED) = '2021'
;

SELECT YEAR(o.sales_date) AS YEAR, MONTH(o.sales_date) AS MONTH, COUNT(DISTINCT o.user_id) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT o.user_id)/(SELECT COUNT(user_id)
            FROM USER_INFO
            WHERE YEAR(JOINED) = '2021'),1) AS PURCHASED_RATIO
FROM USER_INFO u
RIGHT JOIN ONLINE_SALE o ON u.USER_ID=o.USER_ID
WHERE YEAR(u.JOINED) = '2021'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH
;