-- 코드를 입력하세요
SELECT BOOK_ID, SUM(SALES)
FROM BOOK_SALES
WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY BOOK_ID
;

SELECT b.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(price*j.SALES) AS TOTAL_SALES
FROM BOOK b
LEFT JOIN AUTHOR a ON b.author_id=a.author_id
LEFT JOIN (
    SELECT BOOK_ID, SUM(SALES) AS SALES
    FROM BOOK_SALES
    WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    GROUP BY BOOK_ID
    ) j ON b.book_id=j.book_id
GROUP BY b.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY
ORDER BY b.AUTHOR_ID, b.CATEGORY DESC
;

